[project]
name = "radioedit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audio-separator[gpu]>=0.36.1",
    "gradio>=5.49.0",
    "openai-whisper>=20250625",
    "srt>=3.5.3",
    "whisper-timestamped>=1.15.8",
]
